= The Holy Hand Grenade of Antioch (in AsciiRFC)

image:https://img.shields.io/travis/riboseinc/rfc-camelot-holy-grenade/master.svg[
	Build Status, link="https://travis-ci.org/riboseinc/rfc-camelot-holy-grenade"]

This Internet-Draft is written in
https://datatracker.ietf.org/doc/draft-ribose-asciirfc/[AsciiRFC]
using the excellent
https://github.com/riboseinc/asciidoctor-rfc[`asciidoctor-rfc` gem].

== Quick Start

For a blank slate start of your Internet-Draft written in AsciiRFC:

1. Simply clone this repository 
2. Copy out all the files (including the dot-files) 
3. Done!

== Usage

=== Fetching The Document

[source,sh]
----
git clone https://github.com/riboseinc/rfc-camelot-holy-grenade
----

=== Installing Build Tools

You will need Ruby, `xml2rfc` and `idnits` (for submission preflight).

=== On macOS

[source,sh]
----
brew install idnits
brew install python
easy_install pip
pip install -r requirements.txt
gem install bundler
bundle install
----

=== Building The Document

[source,sh]
----
make all
# or
export ID_NAME=camelot-holy-grenade
make draft-${ID_NAME}.txt
----

=== Checking Against idnits

https://tools.ietf.org/tools/idnits/[idnits] is the RFC checking tool
prior to submissions.

The `make` target finds exactly the document name from the `:name:`
document attribute and puts the file in the right place before calling
`idnits` to prevent it complaining about the location.

[source,sh]
----
export ID_NAME=camelot-holy-grenade
make draft-${ID_NAME}.nits
----

=== Checking For Invalid / Unicode Characters

[source,sh]
----
export ID_NAME=camelot-holy-grenade
pcregrep --color='auto' -n "[\x80-\xFF]" draft-${ID_NAME}.xml
----

=== Iterating The Document

[source,sh]
----
export ID_NAME=camelot-holy-grenade
make clean all; open draft-${ID_NAME}.txt
----

